#![deny(missing_docs)]

/// Possible commands that can be generated by the `afrim-preprocessor`.
#[derive(Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum Command {
    /// Request to commit a text.
    CommitText(String),
    /// Request to pause the listener.
    Pause,
    /// Request to resume the listener.
    Resume,
    /// Request to delete the last insertion.
    Delete(String),
}
